### ISSUE TITLE
归档页文章贡献echart图问题

### ISSUE THREAD

**Issue by QiaofengKuo** [removeif/hexo-theme-icarus-removeif#2]
您好，我借鉴你的模板建造我的归档页后，发现echarts图加载不出来，我完全复制了layout/archive.ejs,在source/js也添加了echarts.min.js，能帮我看看吗，本人qq：295312534

**Comment by removeif** [comment]
现在有点事，你把博客代码上传到github上，给我地址，一会儿我给你看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Crazy <notifications@github.com&gt;
发送时间: 2019年10月24日 20:03
收件人: removeif/hexo-theme-icarus-removeif <hexo-theme-icarus-removeif@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[removeif/hexo-theme-icarus-removeif] 归档页文章贡献echart图问题 (#2)




您好，我借鉴你的模板建造我的归档页后，发现echarts图加载不出来，我完全复制了layout/archive.ejs,在source/js也添加了echarts.min.js，能帮我看看吗，本人qq：295312534

**Comment by removeif** [comment]
> 您好，我借鉴你的模板建造我的归档页后，发现echarts图加载不出来，我完全复制了layout/archive.ejs,在source/js也添加了echarts.min.js，能帮我看看吗，本人qq：295312534
对了，我想起了，你看下是不是没有引入jquery,应该是需要引入jquery的

**Comment by removeif** [comment]
@QiaofengKuo

**Comment by QiaofengKuo** [comment]
谢谢你的建议，但我还没解决到，已上传源码到github：https://github.com/QiaofengKuo/theme-icarus.git，帮我看看，那里添加少了

**Comment by removeif** [comment]
> 谢谢你的建议，但我还没解决到，已上传源码到github：[https://github.com/QiaofengKuo/theme-icarus.git，帮我看看，那里添加少了](https://github.com/QiaofengKuo/theme-icarus.git%EF%BC%8C%E5%B8%AE%E6%88%91%E7%9C%8B%E7%9C%8B%EF%BC%8C%E9%82%A3%E9%87%8C%E6%B7%BB%E5%8A%A0%E5%B0%91%E4%BA%86)
@QiaofengKuo themes/hexo-theme-icarus/source/css/style.styl文件中加上以下代码
```css themes/hexo-theme-icarus/source/css/style.styl
#post-calendar {
    display: flex;
    justify-context: center;
    align-items: center;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 200px;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}

.post-calendar-pre
    overflow-x: auto;
    justify-content: center;
    max-width: 100%;
```
