### ISSUE TITLE
social link邮件显示

### ISSUE THREAD

**Issue by NavePnow** [removeif/hexo-theme-icarus-removeif#4]
您好，请问一下主页邮件链接的icon格式是什么呀，我在demo里面没有找到诶。
谢谢

**Comment by removeif** [comment]
嗯，博客中的是以下这几个
```yaml
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/removeif'
            Email:
                icon: fa fa-envelope
                url: 'mailto:removeif@163.com'
            Weibo:
                icon: fab fa-weibo
                url: 'https://weibo.com/u/3050419984'
            Qq:
                icon: fab fa-qq
                url: 'https://github.com/removeif'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
```
