### ISSUE TITLE
使用 Travis 自动部署

### ISSUE THREAD

**Issue by NavePnow** [removeif/hexo-theme-icarus-removeif#6]
您好，
我今下午尝试了利用 [Travis](https://travis-ci.org/) 自动部署，但是每次部署之后打开网页都不能正常显示（一片空白），不知道什么原因，如果你有空的话，能帮忙尝试一下么，我感觉还挺方便的，利用自动部署就不用在本机 hexo g -d了。
谢谢

**Comment by removeif** [comment]
> 您好，
> 我今下午尝试了利用 [Travis](https://travis-ci.org/) 自动部署，但是每次部署之后打开网页都不能正常显示（一片空白），不知道什么原因，如果你有空的话，能帮忙尝试一下么，我感觉还挺方便的，利用自动部署就不用在本机 hexo g -d了。
> 谢谢

@NavePnow 我照着网上的教程，最后一步推送代码时报错
```js
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/removeif/removeif.github.io.git/'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/removeif/removeif.github.io.git/'
    at ChildProcess.<anonymous> (/home/travis/build/removeif/blog_back_20190621/node_modules/hexo-util/lib/spawn.js:37:17)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
Done. Your build exited with 0.
```
travis配置文件
```yaml
# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js:
  - 11.1.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
#branches:
#  only:
#    - master

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "removeif"
  - git config user.email "980099577@163.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
```
_config.yml配置
```yaml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
#  repo: https://github.com/removeif/remove.io.git
  repo: https://gh_token@github.com/removeif/removeif.github.io.git
  branch: master
```
感觉没问题了，实在不知道哪里的问题，你帮我看下哪里还漏了啥，是还要ssh密钥？

**Comment by NavePnow** [comment]
巧了，怕不是看的一篇，不过感觉配置有点少，应该是你的环境变量出问题了，我明天把我的配置发你。
BTW: 我的博客渲染出问题了 555
hexo server可以 但一部署网页看不到： nave.work 求救大佬（

**Comment by removeif** [comment]
> 巧了，怕不是看的一篇，不过感觉配置有点少，应该是你的环境变量出问题了，我明天把我的配置发你。
> BTW: 我的博客渲染出问题了 555
> hexo server可以 但一部署网页看不到： nave.work 求救大佬（

你的感觉是资源文件，js那些没部署上去，可以看下具体的自动部署的日志，应该有打印信息

**Comment by NavePnow** [comment]
如果是手动部署的呢，就hexo g -d，可以看么

**Comment by removeif** [comment]
> 如果是手动部署的呢，就hexo g -d，可以看么
@NavePnow 怎么手动部署，不是推上去后就自动部署了嘛

**Comment by removeif** [comment]
> 如果是手动部署的呢，就hexo g -d，可以看么
@NavePnow 
我的可以了，之前的token有问题，重新生成了一个就好了。配置你可以参考下，部署后也能正常访问
```yaml
# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js:
  - 11.1.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
#branches:
#  only:
#    - master

before_install:
#  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
#  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
#  - git config user.name "removeif"
#  - git config user.email "removeif@163.com"
#  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
#  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
#  - cat ./_config.yml
#  - ls
#  - pwd
#  - ls public
#  - hexo deploy
  - cd ./public
  - git init
  - git config user.name "removeif"
  - git config user.email "removeif@163.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@github.com/removeif/removeif.github.io.git" master:master
```
